### ISSUE TITLE
Add installation instructions

### ISSUE THREAD

**Issue by Gowiem** [maxgoedjen/secretive#101]
## Info

I came here from Hacker News. I'd be interested in checking out the tool, but I'm not sure where to get it considering the README doesn't mention anyway to install it. I'm assuming I should head over to releases, but maybe it's also on the App Store or installable via Brew or a simple bash script?

I believe you'll get better transaction if you add this type of info to your README. 👍

**Comment by maxgoedjen** [comment]
Good suggestion @Gowiem – I have no plans to add MAS support at this time (mostly due to concerns over the ability to compare the thing you download to the source code that generated it). I've added a link to the releases page in the FAQ. There is also a homebrew formula, though I do not personally maintain it (I have a ticket open to automate generating new brew releases as part of the CI process but I haven't gotten around to investigating it.

**Comment by Gowiem** [comment]
@maxgoedjen Thanks! 👍
