### ISSUE TITLE
support curve25519

### ISSUE THREAD

**Issue by obogobo** [maxgoedjen/secretive#109]
It appears as if curve25519 keys can be generated in the secure enclave: https://developer.apple.com/documentation/security/certificate_key_and_trust_services/keys/storing_keys_in_the_secure_enclave

is it feasible to expose support for this via secretive?

**Comment by maxgoedjen** [comment]
So this is kinda interesting – I _THINK_ the Secure Enclave should be able to store those keys (it for sure can _perform operations_ on them, I'm just not sure it can store them. The [docs](https://developer.apple.com/documentation/cryptokit/storing_cryptokit_keys_in_the_keychain) certainly suggest that should be possible.

Two main issues (neither insurmountable):
1: As far as I can tell, curve25519 is _only_ supported with CryptoKit's API instead of direct keychain access (which is what Secretive currently uses). I'd need to check into how stuff like backwards compatibility would work here.
2: I'll need to implement ed25519 signing (again, should be reasonably doable with CryptoKit) and OpenSSH formatting (if it's similar to ECDSA that's not a problem, but I haven't done the research there. RSA is pretty different and I haven't bothered with it yet for that reason).

**Comment by maxgoedjen** [comment]
So I've been playing with this a bit more – it's got some weird compromises that I'm not sure how I feel about. 

In short: when I generate a ecdsa key, it's generated entirely in the Secure Enclave, not in application memory.
Curve25519 behaves differently – you have to create it with CryptoKit, and when you do, the private key exists in application memory, and it's [directly readable](https://developer.apple.com/documentation/cryptokit/curve25519/signing/privatekey/3344735-rawrepresentation). This is a reasonably small attack surface, but it's definitely vulnerable to a class of attacks that ECDSA keys aren't. Obviously Curve25519 is theoretically a more foolproof curve in terms of IRL signing, so this tradeoff may be worth it. I'm sort of undecided at the moment. If anyone has strong feelings/arguments one way or the other, feel free to post/vote (we'll say 🚀for "add Curve25519 despite limitations," 😕 for "leave it."

After playing with it, I'm still not entirely sure you _can_ store curve25519 keys in the SEP – you can store them in the Keychain, but AFAICT you still can't import preexisting keys into the SEP. The docs are just misleading, I think.

**Comment by rollcat** [comment]
My $.03:

- I'd always prefer Ed25519 over anything else.
- I'd always prefer to use almost anything else over ECDSA.
- Generating private keys in userland and/or import functionality is an acceptable trade-off. Still miles and miles ahead of storing them directly in the local filesystem.

**Comment by maxgoedjen** [comment]
Yeah given real world attack surface I'm inclined to think it MIGHT be a worthwhile trade off - experimentally though I still can't get it working, which kind of lines up with my expectations (that you can't import keys into the SEP). I think the top article linked is just kinda misleading and kinda conflates the keychain and the SEP. You can definitely store them in the keychain, but not in the SEP afaict.

**Comment by maxgoedjen** [comment]
Since it's looking like this isn't technically possible at the moment, I'm gonna close this one out. I'll keep an eye for support for it in Keychain in future versions (I've filed FB8721118 requesting this). Feel free to reopen if this changes, I'll keep an eye out too.
