### ISSUE TITLE
Timed Biometric Requirement

### ISSUE THREAD

**Issue by lvangool** [maxgoedjen/secretive#320]
It would be perfect to have a middle-ground between "requires authentication" and "authentication not required" (ie. "requires authentication every x hours")
Currently, for git-heavy workflows, "requires authentication" means touching the fingerprint 50 times a day.

Ps. Secretive is great - fantastic job!

**Comment by taxilian** [comment]
I came on to ask for the same thing, but @lvangool beat me to it =]

With my smart cards I can set it so that when I unlock it it stays unlocked for e.g. up to 2 hours (unless it's removed) and then I need to put in the key again; I think that would be (for me) the perfect blend between security and convenience. I dislike having to use touchid with every single git command, but I also am uncomfortable leaving the key unlocked any time my computer is logged in.

I could definitely help test this, I have all the tools to build it, but my swift experience is not sufficient to implement it or I'd offer to help. If you want to give me pointers where to look I could take a stab, maybe. Thanks for doing this project! sekey was nice, but seems to be abandoned, and this seems like a better project anyway.

**Comment by maxgoedjen** [comment]
This is actually implemented in main now (#252) I just haven't shipped it yet. If you grab a recent "release" run from the actions tab, it'll have it. I'm just trying to shake out a few issues around premature expiration  before I push it out.

**Comment by taxilian** [comment]
Nice! I might just do that =] now if I could just change the priority so it would use the card first if it's inserted.... ;-) but I can raise another ticket for that

**Comment by lvangool** [comment]
@maxgoedjen very cool - thank you!

**Comment by chancez** [comment]
Atm secretive is pretty unusable for me without some kind of authorization caching, as I have some tools which end up triggering a `git fetch` multiple times and secretive prompts me like 50+ times in a row each time. In particular:
- `gopls` (language server for Go) is calling `go mod tidy`
- `go mod tidy` calls `git fetch`, then `git ls-remote`, then `git fetch`..., seemingly it repeats this in a loop for a number of different inputs (I'm honestly not super sure what it's iterating over).

**Comment by taxilian** [comment]
@chancez This is already out in the latest release; click the "leave unlocked" dropdown on the notice in the top right corner of the screen and choose your length of time, it'll prompt you to authorize again and then it'll remember for that length of time. It does seem to need to be done for different process trees, but for the one you're working on it works great for me.

**Comment by chancez** [comment]
I missed this was already in release, however I installed via brew, and was not getting any drop down notices. 

Additionally, I'd rather not have to use a notification prompt for this, but configure it once and be done. Eg:
```secretive config authorization-ttl 8h``` once on the device and then after my first authorization, it wouldn't prompt me again for 8 hours. I think there's another issue for this.

**Comment by maxgoedjen** [comment]
@chancez there's some architectural issues that make this a bit difficult at the moment, but it's still something I'm thinking about for the future. Tracking that separately here, FWIW #358
