### ISSUE TITLE
Public keys go missing after MacOS update to (13.1)

### ISSUE THREAD

**Issue by NoxHarmonium** [maxgoedjen/secretive#426]
Not sure if this is a MacOS issue or a Secretive issue but I'll put this here so other people can find the solution if it happens to them.

*What?*
Just updated to Ventura 13.1 and tried a `git push` and I got an error message like the following:

```
Warning: Identity file /Users/<username>/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/PublicKeys/<hash>.pub not accessible: No such file or directory.
ERROR: Repository not found.
fatal: Could not read from remote repository.
```

I tried listing the key directory and it was empty:

```
ls /Users/<username>/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/PublicKeys
```

I tried listing the Data directory and it seemed to be a symlink to my home directory? 🤷 

```
ls /Users/<username>/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/
Desktop@    Downloads@  Movies@     Pictures@   SystemData/ tmp/
Documents/  Library/    Music@      PublicKeys/ socket.ssh=
```

I opened the Secretive UI and my keys were still listed there. I could still copy the fingerprint etc.

*Solution*

I created a new "dummy" key in the Secretive UI and it somehow "forced" the directory structure to fix itself.

Everything seems to be working now.

I confess that I don't know enough about the inner workings of MacOS (especially in the M1) days so I'm not sure how those directories are mounted, but it is very strange that Secretive could access the keys but I couldn't see them in my terminal.

Sorry I can't help with any more info.

**Comment by andrewdmontgomery** [comment]
I am seeing the same behavior immediately after updating to 13.1.

I hope to come back to this when I have more time, later today.  But for now, I wanted to pass along what little debugging I could do quickly.

I tried manually creating the `.pub` files using the paths and contents I copied from the Secretive UI:
1. Copying the public key string adds two new line characters, which leaves the key invalid:
   - One at the end of the line
   - One immediately following the public key string (before the email address ID)
2. Authentication still failed when attempting to use this key

I have the following configuration in my `~/.ssh/config`:
```
Host github.com
  User git
  PreferredAuthentications publickey
  IdentityFile ~/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/PublicKeys/824857adc36dc2bc42df303c2dd2913e.pub
  IdentityAgent ~/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh
```

```
$ ssh -v git@github.com

...
debug1: Offering public key: /Users/andrew/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/PublicKeys/824857adc36dc2bc42df303c2dd2913e.pub ECDSA SHA256:+uXJwjiHrjF8WK5FMi70626weDOi/FpmSlastgsIitE explicit
debug1: Server accepts key: /Users/andrew/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/PublicKeys/824857adc36dc2bc42df303c2dd2913e.pub ECDSA SHA256:+uXJwjiHrjF8WK5FMi70626weDOi/FpmSlastgsIitE explicit
Load key "/Users/andrew/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/PublicKeys/824857adc36dc2bc42df303c2dd2913e.pub": invalid format
...
```

So then I made a switch.  When I first started using Secretive, it did not automatically generate this public key file at this path.  So back then, I manually created that key and saved it in `~/.ssh/secretive-github.pub`.  When Secretive introduced the ability to automatically generated public keys, I reconfigured my `~/.ssh/config` to use those new paths.  But I left the original public key files in place, untouched.

I have the same problem with those untouched public keys.

So I tried creating a new dummy key in the Secretive UI:
- All public keys were updated (new timestamp on all `.pub` files)
- It now works

So the problem is more than just having those public keys missing.

**Comment by maxgoedjen** [comment]
There's _something_ weird with how macOS relaunches `SecretAgent` (which is responsible for both handling requests + generating that public key directory) after a system update. We've got at least one or two tickets around this hanging around (https://github.com/maxgoedjen/secretive/issues/397, and a handful of others) – but it's definitely something I'm aware of.

FWIW, easy fix (although obviously not one I'm _happy_ with) is just force quitting `SecretAgent` in activity monitor.

**Comment by maxgoedjen** [comment]
@saagarjha suggested this might be caused by macOS relaunching the agents earlier during update than during a reboot – so early, that it might be before the keychain was unlocked. 

This lines up with a couple points we've been seeing here:
- Agent is live, but acting as if it has no keys
- Creating a new key causes it to reload: https://github.com/maxgoedjen/secretive/blob/main/Sources/Packages/Sources/SecureEnclaveSecretKit/SecureEnclaveStore.swift#L71

I'm trying to reproduce upgrade conditions using a VM to see if I can verify that that's specifically what's going on, but I think it's pretty likely. Easy fix too – basically if we get an operation and have no keys loaded, we'll just call reload.

**Comment by maxgoedjen** [comment]
@louwers is the public keys _directory_ present? I was just recently running into #475 where the directory itself wasn't being created. I think there's two separate issues: that one, and one where it does exist but fails to write.
