### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by WilliamB17** [maxgoedjen/secretive#92]
Hi,

Today, I use multiple keys, for different hosts, and I set my configuration as follows (in `~/.ssh/config`): 

```
Host gitlab.com
 HostName gitlab.com
 AddKeysToAgent yes
 UseKeychain yes
 IdentityFile ~/.ssh/id_rsa
 UserKnownHostsFile ~/.ssh/known_hosts

Host *host.net
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/id_rsa
  UserKnownHostsFile ~/.ssh/known_hosts

Host gitlab.com-perso
  HostName gitlab.com
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/id_rsa_perso
  UserKnownHostsFile ~/.ssh/known_hosts

Host nerves.local
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/id_rsa_nerves
  UserKnownHostsFile ~/.ssh/known_hosts

Host *192.168.1*
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/id_rsa_perso
  UserKnownHostsFile ~/.ssh/known_hosts
```

How to do the same thing with Secretive? I can't indicate the `IdentifyFile` value ?

**Comment by maxgoedjen** [comment]
Hey @WilliamB17, you can't specify an `IdentityFile` for a specific key in Secretive (since it's not actually "file" backed), but the right key should just be automatically selected if completed both steps in the tutorial (setting up the daemon and adding the shell config line). Is it not selecting the right key for you?

**Comment by Hamuko** [comment]
>Is it not selecting the right key for you?

How does Secretive _select_ the key? Because running `ssh -v` with Secretive makes it look like it just iterates from the first key onwards until it finds a key that the server will accept, meaning it's not really selecting anything.

The idea behind specifying two hosts for the same HostName in regards to git is that you can force SSH to use a particular key when using it with git. That allows using different accounts with different SSH keys on the same machine. Going to assume that William has a work account and a personal account (gitlab.com/id_rsa and gitlab.com-perso/id_rsa_perso).

```
git clone git@gitlab.com:work/project.git
git clone git@gitlab.com-perso:personal/project.git
```

The first will connect to `git@gitlab.com` using the key `~/.ssh/id_rsa` while the second will connect to `git@gitlab.com` using the key `~/.ssh/id_rsa_perso`.

If Secretive only uses the first acceptable key, it'll always just choose the first key that is associated with _a_ Gitlab account, since they all have the right to authenticate against `git@gitlab.com`. In this case it'd probably be William's work account and he'd be unable to clone anything from his personal account, since Gitlab doesn't give any access rights to `git@gitlab.com:personal/project.git` to his work account.

Granted, I have not delved too deeply into how Secretive or SSH agents work, so this is largely conjecture. I just found this issue since I was curious if you could associate keys like you can do with `IdentityFile`.

**Comment by martinh2011** [comment]
I use a Yubikey 5c and gpg-agent as ssh-agent. I have stored the public key in .ssh/id-yubikey5c.pub. That way I can specify the public key file in .ssh/config as IdentityFile and the signing request ssh-agent gets requests the correct key.

This should work with secretive, too. Try copying the public key as shown in the secretive app, save it into a file in .ssh/ and use that file as IdentityFile.

**Comment by Hamuko** [comment]
Are you sure? Everything I know about `IdentityFile` is that it's the private key. And if I do this, I'm not seeing any difference when running `ssh -v`.

```
debug1: Offering public key: ecdsa-sha2-nistp256 ECDSA SHA256:1 agent
debug1: Authentications that can continue: publickey,password
debug1: Offering public key: ecdsa-sha2-nistp256 ECDSA SHA256:2 agent
debug1: Authentications that can continue: publickey,password
debug1: Offering public key: ecdsa-sha2-nistp256 ECDSA SHA256:3 agent
debug1: Server accepts key: ecdsa-sha2-nistp256 ECDSA SHA256:3 agent
debug1: Authentication succeeded (publickey).
```

The correct key for this server was added as the third key in Secretive.
